# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3affe406b67f1dcec5ce4bcb2dd074b3803205f62ca64a82bf91f1e1715a0539b17b14f0be20101ccde07ca44093a6e64a5e2b160610ed316a4d062baf23a10

test:
  secret_key_base: 9c07c6e40a3796e4878ef4b6760eee108751148c83e49021d8ff9c53b1144eef7b98e72276ef3925742eb3e91e18082e8d565ed075c3970f790fde4c5ded39e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
